-- DATABASE UPGRADE FOR PROFESSIONAL ADMIN DASHBOARD
-- Run this in your Supabase SQL Editor to add missing fields for stock, descriptions, and affiliate tracking.

-- 1. Upgrade Products table
ALTER TABLE public.products 
ADD COLUMN IF NOT EXISTS description TEXT,
ADD COLUMN IF NOT EXISTS stock INTEGER DEFAULT 0,
ADD COLUMN IF NOT EXISTS is_affiliate BOOLEAN DEFAULT FALSE,
ADD COLUMN IF NOT EXISTS affiliate_url TEXT;

-- 2. Upgrade Courses table
ALTER TABLE public.courses
ADD COLUMN IF NOT EXISTS image TEXT;

-- 3. Upgrade Gallery table
-- (Already has Caption and Order)

-- 4. Upgrade Orders table
-- (Ensure it can handle course IDs and user IDs for filtering)
ALTER TABLE public.orders
ADD COLUMN IF NOT EXISTS order_type TEXT DEFAULT 'Product', -- 'Product' or 'Course'
ADD COLUMN IF NOT EXISTS email TEXT; -- For User Dashboard filtering

-- 5. Upgrade Enrollments table
ALTER TABLE public.enrollments
ADD COLUMN IF NOT EXISTS email TEXT; -- For User Dashboard filtering

-- 6. Create Categories table (Dynamic Management)
CREATE TABLE IF NOT EXISTS public.categories (
  id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  name TEXT UNIQUE NOT NULL,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Seed initial categories if empty
INSERT INTO public.categories (name) 
VALUES ('Resin'), ('Painting'), ('Jewelry'), ('Handmade'), ('Artist Essentials')
ON CONFLICT (name) DO NOTHING;

-- Disable RLS for now for easy development (User should enable it with policies later)
ALTER TABLE public.categories DISABLE ROW LEVEL SECURITY;

