-- ARTICLES / BLOGS TABLE SETUP
-- Ensure the blogs table is ready for rich text content

-- 1. Create the table if it doesn't exist (robust)
CREATE TABLE IF NOT EXISTS public.blogs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title TEXT NOT NULL,
    excerpt TEXT,
    content TEXT NOT NULL, -- This will store HTML
    img TEXT, -- Cover image URL
    date TEXT,
    author TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    comments JSONB DEFAULT '[]'::jsonb
);

-- 2. Add RLS (Row Level Security)
ALTER TABLE public.blogs ENABLE ROW LEVEL SECURITY;

-- 3. Allow Public to view articles
CREATE POLICY "Public View Articles"
ON public.blogs FOR SELECT
USING (true);

-- 4. Allow Authenticated users to manage articles
CREATE POLICY "Admin Manage Articles"
ON public.blogs FOR ALL
USING (auth.role() = 'authenticated');
