-- SUPABASE SETUP SCRIPT FOR ART SOCIETY
-- Please run this entire script in your Supabase SQL Editor to create your database and migrate all your existing data exactly as it was.

-- 1. Create Tables
CREATE TABLE public.products (
  id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  name TEXT NOT NULL,
  price NUMERIC NOT NULL,
  discount_price NUMERIC,
  category TEXT NOT NULL,
  img TEXT NOT NULL,
  is_visible BOOLEAN DEFAULT TRUE NOT NULL
);

CREATE TABLE public.testimonials (
  id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  name TEXT NOT NULL,
  text TEXT NOT NULL,
  rating INTEGER NOT NULL
);

CREATE TABLE public.blogs (
  id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  title TEXT NOT NULL,
  date TEXT NOT NULL,
  excerpt TEXT NOT NULL,
  img TEXT NOT NULL,
  content TEXT NOT NULL
);

CREATE TABLE public.orders (
  id TEXT PRIMARY KEY,
  customer TEXT NOT NULL,
  item TEXT NOT NULL,
  amount NUMERIC NOT NULL,
  status TEXT NOT NULL,
  date TEXT NOT NULL
);

CREATE TABLE public.users (
  id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  name TEXT NOT NULL,
  email TEXT NOT NULL,
  role TEXT NOT NULL,
  joined TEXT NOT NULL
);

CREATE TABLE public.courses (
  id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  title TEXT NOT NULL,
  price NUMERIC NOT NULL,
  first_month NUMERIC NOT NULL,
  tag TEXT NOT NULL,
  duration TEXT NOT NULL,
  batches TEXT[] NOT NULL,
  "desc" TEXT NOT NULL,
  is_active BOOLEAN DEFAULT TRUE NOT NULL
);

CREATE TABLE public.enrollments (
  id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  student_name TEXT NOT NULL,
  phone TEXT NOT NULL,
  course_id BIGINT REFERENCES public.courses(id),
  course_name TEXT NOT NULL,
  batch TEXT NOT NULL,
  payment_status TEXT NOT NULL,
  enrolled_date TEXT NOT NULL,
  type TEXT NOT NULL
);

CREATE TABLE public.affiliates (
  id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  name TEXT NOT NULL,
  img TEXT NOT NULL,
  url TEXT NOT NULL,
  price NUMERIC NOT NULL,
  is_active BOOLEAN DEFAULT TRUE NOT NULL
);

CREATE TABLE public.gallery (
  id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  url TEXT NOT NULL,
  caption TEXT NOT NULL,
  "order" INTEGER NOT NULL
);

-- Turn off Row Level Security (RLS) so the frontend can read/write data easily without complex auth policies initially.
ALTER TABLE public.products DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.testimonials DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.blogs DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.orders DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.users DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.courses DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.enrollments DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.affiliates DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.gallery DISABLE ROW LEVEL SECURITY;

-- 2. Insert Data (Migrating from mockData.js)
INSERT INTO public.products (id, name, price, discount_price, category, img, is_visible) VALUES
(1, 'Crochet Sunflower Bouquet', 2900, null, 'Handmade', 'https://images.unsplash.com/photo-1584589167171-541ce45f1eea?auto=format&fit=crop&q=80&w=800', true),
(2, 'Resin Heart Pendant Necklace', 2900, 2000, 'Jewelry', 'https://images.unsplash.com/photo-1601121141461-9d6647bca1ed?auto=format&fit=crop&q=80&w=800', true),
(3, 'Custom Resin Photo Plaque', 5400, null, 'Resin', 'https://images.unsplash.com/photo-1550684848-fac1c5b4e853?auto=format&fit=crop&q=80&w=800', true),
(4, 'Anniversary Calendar Plaque', 5800, null, 'Resin', 'https://images.unsplash.com/photo-1543857778-c4a1a3e0b2eb?auto=format&fit=crop&q=80&w=800', true),
(5, 'Floral Hexagon Bracelet', 3300, 2500, 'Jewelry', 'https://images.unsplash.com/photo-1611085583191-a3b181a88401?auto=format&fit=crop&q=80&w=800', true),
(6, 'Custom Couple Resin Frame', 7000, null, 'Resin', 'https://images.unsplash.com/photo-1513364776144-60967b0f800f?auto=format&fit=crop&q=80&w=800', true),
(7, 'Krishna Yashoda Fabric Painting', 12000, 10000, 'Painting', 'https://images.unsplash.com/photo-1579783902614-a3fb3927b6a5?auto=format&fit=crop&q=80&w=800', true),
(8, 'Red Petal Resin Earrings', 1800, null, 'Jewelry', 'https://images.unsplash.com/photo-1515562141207-7a88fb7ce338?auto=format&fit=crop&q=80&w=800', true),
(9, 'Professional Paintbrushes', 1250, null, 'Artist Essentials', '/images/products/paintbrushes.png', true),
(10, 'Mixing Palette / Paint Tray', 850, 650, 'Artist Essentials', '/images/products/palette.png', true),
(11, 'Premium Cotton Canvas', 1500, null, 'Artist Essentials', '/images/products/canvas.png', true),
(12, 'Sculpting & Art Tools', 2200, null, 'Artist Essentials', '/images/products/sculpting_tools.png', true),
(13, 'Sketchbook & Pencils', 1100, 950, 'Artist Essentials', '/images/products/sketchbook.png', true),
(14, 'Custom Couple Resin Calendar', 3500, null, 'Resin', '/images/products/couple_calendar.jpg', true),
(15, 'Resin Couple Memory Frame', 4200, 3800, 'Resin', '/images/products/couple_resin_frame.jpg', true),
(16, 'Circular Photo Wall Hanging', 5500, null, 'Handmade', '/images/products/couple_wall_hanging.jpg', true),
(17, 'Resin Heart Pendant Necklace', 1200, 950, 'Jewelry', '/images/products/heart_pendant_necklace.jpg', true),
(18, 'Rose Petal Resin Earrings', 850, null, 'Jewelry', '/images/products/rose_petal_earrings.jpg', true),
(19, 'Handmade Floral Resin Bracelet', 650, null, 'Handmade', '/images/products/resin_floral_bracelet.jpg', true),
(20, 'Resin Couple Flower Frame', 3800, null, 'Handmade', '/images/products/couple_resin_frame2.jpg', true),
(21, 'Handmade Crochet Sunflower Bouquet', 1500, null, 'Handmade', '/images/products/crochet_sunflower_bouquet.jpg', true),
(22, 'Custom Resin Nail Plaque', 1100, null, 'Handmade', '/images/products/resin_nail_coaster.jpg', true);

-- Fix Sequence after explicit ID inserts
SELECT setval('products_id_seq', (SELECT MAX(id) FROM products));

INSERT INTO public.testimonials (id, name, text, rating) VALUES
(1, 'Sarah Jenkins', 'Mahi turned my parents'' old wedding photo into a breathtaking charcoal sketch. I cried when I saw it.', 5),
(2, 'David Chen', 'The resin coasters I ordered for my new home are stunning. True craftsmanship and attention to detail.', 5),
(3, 'Priya Patel', 'I ordered a custom oil painting of my dog who passed away. The emotional connection in the eyes was captured perfectly.', 5);
SELECT setval('testimonials_id_seq', (SELECT MAX(id) FROM testimonials));

INSERT INTO public.blogs (id, title, date, excerpt, img, content) VALUES
(1, 'The Magic of Preserving Flowers in Resin', 'April 2, 2026', 'Learn how we take your wedding bouquets and turn them into eternal keepsakes...', 'https://images.unsplash.com/photo-1507290439931-a861b5a38200?auto=format&fit=crop&q=80&w=800', 'Preserving your wedding bouquet is a beautiful way to hold onto the magic of your special day. At Art Society, we specialize in casting those delicate petals into crystal-clear resin, creating functional art pieces like coasters, ring holders, and decorative blocks.
The process begins the moment you send us your freshly dried flowers. We carefully arrange them, pouring layers of high-quality, UV-resistant resin. This meticulous layering prevents bubbles and ensures the flowers retain their depth and vibrant colors.
Whether it''s a rose from your first date or the centerpiece from your wedding reception, resin art transforms fleeting moments into timeless heirlooms. It''s not just home decor; it''s a frozen piece of time that you can look at and touch every single day.');
SELECT setval('blogs_id_seq', (SELECT MAX(id) FROM blogs));

INSERT INTO public.orders (id, customer, item, amount, status, date) VALUES
('#1042', 'Sarah Jenkins', 'Custom Watercolor (A4)', 6500, 'Pending', 'Apr 4, 2026'),
('#1041', 'David Chen', 'Resin Ocean Coasters', 3700, 'Shipped', 'Apr 2, 2026'),
('#1040', 'Priya Patel', 'Custom Oil (A3)', 18500, 'In Progress', 'Mar 30, 2026');

INSERT INTO public.users (id, name, email, role, joined) VALUES
(1, 'Admin', 'admin@artsociety.com', 'Admin', 'Jan 1, 2026'),
(2, 'Sarah Jenkins', 'sarah.j@example.com', 'Customer', 'Mar 15, 2026'),
(3, 'David Chen', 'dchen99@example.com', 'Customer', 'Apr 1, 2026'),
(4, 'Emma Wilson', 'emma.w@example.com', 'Customer', 'Apr 5, 2026'),
(5, 'Priya Sharma', 'priya.s@example.com', 'Student', 'Apr 8, 2026'),
(6, 'Anjali Mehta', 'anjali.m@example.com', 'Student', 'Apr 9, 2026');
SELECT setval('users_id_seq', (SELECT MAX(id) FROM users));

INSERT INTO public.courses (id, title, price, first_month, tag, duration, batches, "desc", is_active) VALUES
(1, 'Basic Painting', 500, 800, 'Beginner', '3 months', '{"Morning", "Evening"}', 'Fundamentals of painting, color theory, and brush techniques.', true),
(2, 'Acrylic Painting', 900, 1200, 'Intermediate', '4 months', '{"Morning", "Afternoon"}', 'Advanced acrylic techniques and creative compositions.', true),
(3, 'Lippan Art', 900, 1200, 'Creative', '2 months', '{"Afternoon", "Evening"}', 'Traditional and modern decorative Lippan art.', true),
(4, 'Embroidery', 900, 1200, 'Creative', '3 months', '{"Morning"}', 'Hand embroidery techniques for decorative art.', true),
(5, 'Fabric Painting', 900, 1200, 'Creative', '2 months', '{"Evening"}', 'Paint on fabrics for wearable and decorative art.', true);
SELECT setval('courses_id_seq', (SELECT MAX(id) FROM courses));

INSERT INTO public.enrollments (id, student_name, phone, course_id, course_name, batch, payment_status, enrolled_date, type) VALUES
(1, 'Priya Sharma', '+91 98765 43210', 1, 'Basic Painting', 'Morning', 'Paid', 'Apr 8, 2026', 'Offline'),
(2, 'Anjali Mehta', '+91 87654 32109', 3, 'Lippan Art', 'Evening', 'Pending', 'Apr 9, 2026', 'Online'),
(3, 'Neha Kapoor', '+91 76543 21098', 2, 'Acrylic Painting', 'Morning', 'Paid', 'Apr 10, 2026', 'Offline');
SELECT setval('enrollments_id_seq', (SELECT MAX(id) FROM enrollments));

INSERT INTO public.affiliates (id, name, img, url, price, is_active) VALUES
(1, 'Faber-Castell Watercolor Set', 'https://images.unsplash.com/photo-1513364776144-60967b0f800f?auto=format&fit=crop&q=80&w=400', 'https://www.amazon.in', 1499, true),
(2, 'Winsor & Newton Acrylic Set', 'https://images.unsplash.com/photo-1460661419201-fd4cecdf8a8b?auto=format&fit=crop&q=80&w=400', 'https://www.flipkart.com', 2999, true),
(3, 'Artist Easel (Wooden)', 'https://images.unsplash.com/photo-1513364776144-60967b0f800f?auto=format&fit=crop&q=80&w=400', 'https://www.amazon.in', 3500, true);
SELECT setval('affiliates_id_seq', (SELECT MAX(id) FROM affiliates));

INSERT INTO public.gallery (id, url, caption, "order") VALUES
(1, '/images/products/couple_calendar.jpg', 'Custom Couple Calendar', 1),
(2, '/images/products/couple_wall_hanging.jpg', 'Handmade Wall Hanging', 2),
(3, '/images/products/crochet_sunflower_bouquet.jpg', 'Crochet Sunflower', 3),
(4, '/images/products/heart_pendant_necklace.jpg', 'Heart Pendant', 4),
(5, '/images/products/rose_petal_earrings.jpg', 'Rose Petal Earrings', 5);
SELECT setval('gallery_id_seq', (SELECT MAX(id) FROM gallery));
